import { db } from "./db";
import { projects } from "@shared/schema";

const seedData = [
  {
    name: "Jellyfin",
    description: "The Free Software Media System. It puts you in control of managing and streaming your media.",
    category: "Self-Hosted" as const,
    status: "Using" as const,
    url: "https://jellyfin.org/",
    githubUrl: "https://github.com/jellyfin/jellyfin",
    tags: ["media", "streaming", "video"],
    rating: 5,
    notes: "Best replacement for Plex. Completely free and open source.",
    setupNotes: ["Runs great on Docker", "Hardware acceleration needed for transcoding 4K"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "Termux",
    description: "A terminal emulator and Linux environment app for Android.",
    category: "Android Apps" as const,
    status: "Using" as const,
    url: "https://termux.dev/en/",
    githubUrl: "https://github.com/termux/termux-app",
    tags: ["terminal", "linux", "dev"],
    rating: 5,
    notes: "Essential for any Android power user.",
    setupNotes: ["Install from F-Droid, not Play Store", "pkg update && pkg upgrade first thing"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "WSJT-X",
    description: "Software for weak-signal radio communication using protocols like FT8 and FT4.",
    category: "Ham Radio" as const,
    status: "Want to Try" as const,
    url: "https://wsjt.sourceforge.io/wsjtx.html",
    githubUrl: undefined,
    tags: ["ft8", "digital", "vhf"],
    notes: "Need to set up the audio interface first before trying this.",
    setupNotes: ["Requires accurate time sync on PC", "Check audio levels carefully"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "JTDX",
    description: "Alternative to WSJT-X with modified decoding algorithms for FT8/JT65.",
    category: "Ham Radio" as const,
    status: "Want to Try" as const,
    url: "https://sourceforge.net/projects/jtdx/",
    githubUrl: undefined,
    tags: ["ft8", "digital", "hf"],
    notes: "Some say it decodes better on crowded bands.",
    setupNotes: [] as string[],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "KDE Plasma",
    description: "A graphical workspaces environment created by KDE primarily for Linux systems.",
    category: "Customization" as const,
    status: "Using" as const,
    url: "https://kde.org/plasma-desktop/",
    githubUrl: "https://github.com/KDE/plasma-desktop",
    tags: ["desktop", "gui", "wayland"],
    rating: 4,
    notes: "Extremely customizable. Currently using with Wayland on Arch.",
    setupNotes: ["Wayland session is mostly stable now", "Use kvantum for advanced themes"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "Hyprland",
    description: "A dynamic tiling Wayland compositor that doesn't sacrifice on its looks.",
    category: "Customization" as const,
    status: "Want to Try" as const,
    url: "https://hyprland.org/",
    githubUrl: "https://github.com/hyprwm/Hyprland",
    tags: ["tiling", "wayland", "compositor"],
    notes: "Looks amazing but might take time to configure perfectly.",
    setupNotes: ["Needs custom config file", "Waybar is a good companion"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "Syncthing",
    description: "A continuous file synchronization program — peer-to-peer, no cloud middleman.",
    category: "Utilities" as const,
    status: "Using" as const,
    url: "https://syncthing.net/",
    githubUrl: "https://github.com/syncthing/syncthing",
    tags: ["sync", "files", "p2p"],
    rating: 5,
    notes: "Replaced Dropbox for me. Peer to peer is the way to go.",
    setupNotes: ["Set up on phone and desktop", "Battery optimization needs to be disabled on Android"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "Nextcloud",
    description: "A suite of client-server software for creating and using file hosting services.",
    category: "Self-Hosted" as const,
    status: "Archived" as const,
    url: "https://nextcloud.com/",
    githubUrl: "https://github.com/nextcloud/server",
    tags: ["sync", "cloud", "files"],
    rating: 3,
    notes: "Too heavy for just file sync. Switched to Syncthing.",
    setupNotes: ["Requires database setup (MariaDB/PostgreSQL)", "PHP tuning is crucial for performance"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "KDE Connect",
    description: "A tool that allows devices to communicate with each other — clipboard sync, file sending, and more.",
    category: "Utilities" as const,
    status: "Using" as const,
    url: "https://kdeconnect.kde.org/",
    githubUrl: "https://github.com/KDE/kdeconnect-kde",
    tags: ["sync", "clipboard", "remote"],
    rating: 5,
    notes: "Shared clipboard and file sending is magic.",
    setupNotes: ["Open ports 1714-1764 (TCP/UDP) in firewall"],
    alternatives: [] as string[],
    isSeeded: true,
  },
  {
    name: "Kodi",
    description: "A free and open source media player application.",
    category: "Self-Hosted" as const,
    status: "Archived" as const,
    url: "https://kodi.tv/",
    githubUrl: "https://github.com/xbmc/xbmc",
    tags: ["media", "player"],
    rating: 4,
    notes: "Used to use it on a Raspberry Pi, moved to Jellyfin for centralized server.",
    setupNotes: [] as string[],
    alternatives: [] as string[],
    isSeeded: true,
  },
];

export async function seedDatabase() {
  const existing = await db.select().from(projects).limit(1);
  if (existing.length > 0) {
    console.log("Database already seeded, skipping.");
    return;
  }

  console.log("Seeding database with initial projects...");
  
  for (const data of seedData) {
    await db.insert(projects).values({
      name: data.name,
      description: data.description,
      category: data.category,
      status: data.status,
      url: data.url,
      githubUrl: data.githubUrl ?? null,
      tags: data.tags,
      rating: data.rating ?? null,
      notes: data.notes ?? null,
      setupNotes: data.setupNotes,
      alternatives: data.alternatives,
      isSeeded: data.isSeeded,
    });
  }

  console.log(`Seeded ${seedData.length} projects.`);
}
